export const paymentErrorCodes = [
	'payment.amount.limit',
	'payment.card.disabled',
	'payment.card.expired',
	'payment.card.lost',
	'payment.card.number.invalid',
	'payment.card.scheme.not.supported',
	'payment.card.scheme.unknown',
	'payment.card.security.code.invalid',
	'payment.insufficient.funds',
	'payment.integration.disabled',
	'payment.integration.key.unknown',
	'payment.network.error',
	'payment.receiver.blocked',
	'payment.rejected.by.issuer',
	'payment.rejected',
	'td.secure.failed',
	'td.secure.required',
	'payment.amount.limit',
	'payment.card.disabled',
	'payment.card.expired',
	'payment.card.lost',
	'payment.card.number.invalid',
	'payment.card.scheme.not.supported',
	'payment.card.scheme.unknown',
	'payment.card.security.code.invalid',
	'payment.insufficient.funds',
	'payment.integration.disabled',
	'payment.integration.key.unknown',
	'payment.network.error',
	'payment.receiver.blocked',
	'payment.rejected.by.issuer',
	'payment.rejected',
	'td.secure.failed',
	'td.secure.required'
] as const

export type PaymentErrorCode = (typeof paymentErrorCodes)[number]
